apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: oe03yfd3f-go-gitops
  description: This is GitOps manifest for oe03yfd3f-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: oe03yfd3f-go
    backstage.io/kubernetes-id: oe03yfd3f-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: oe03yfd3f-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:oe03yfd3f-go
