apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oe03yfd3f-go
  janus-idp.io/tekton: oe03yfd3f-go
  backstage.io/kubernetes-id: oe03yfd3f-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oe03yfd3f-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
