apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oe03yfd3f-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oe03yfd3f-go 
  name: oe03yfd3f-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: oe03yfd3f-go 
