apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: oe03yfd3f-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-c9884e6a8c.3nsp.p3.openshiftapps.com/rhtap/rhtap-qe:f387948bc43fb3c3c867344730286f30df957e24@sha256:a51fcecf7cd861cc22da57af28c5ba8ea21220de84a0cbad8620fbd5b33ac0fe
          name: container-image
